use anyhow::{anyhow, ensure, Result};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use std::path::Path;

use crate::mcp_lint;
use crate::HermesEngine;

const HEAL_MODEL: &str = "gpt-5-mini";
const INITIAL_ELIGIBLE_RULES: [&str; 3] = ["SAFETY-001", "SAFETY-002", "SAFETY-003"];

#[derive(Debug, Clone, Serialize, Deserialize)]
struct HealingCandidate {
    rule_id: String,
    file_path: String,
    line_start: u64,
    line_end: u64,
    severity: String,
    message: String,
    strategy: String,
}

pub fn tool_heal_violations(
    engine: &HermesEngine,
    project_root: &Path,
    args: &Value,
) -> Result<String> {
    let requested_model = args["model"].as_str().unwrap_or(HEAL_MODEL);
    ensure!(
        requested_model == HEAL_MODEL,
        "TRACK-048 healing is model-locked to {HEAL_MODEL}"
    );

    let dry_run = args["dry_run"].as_bool().unwrap_or(true);
    let max_items = args["max_items"].as_u64().unwrap_or(25) as usize;

    let lint_payload = if args["lint_payload"].is_object() {
        args["lint_payload"].clone()
    } else {
        let mut lint_args = json!({ "mode": "full" });
        if let Some(scope) = args["scope"].as_str() {
            lint_args["scope"] = Value::String(scope.to_string());
        }
        if let Some(severity_min) = args["severity_min"].as_str() {
            lint_args["severity_min"] = Value::String(severity_min.to_string());
        }
        if let Some(rules) = args["rules"].as_array() {
            lint_args["rules"] = Value::Array(rules.clone());
        }

        let lint_text = mcp_lint::tool_lint_architecture(engine, project_root, &lint_args)?;
        serde_json::from_str::<Value>(&lint_text)
            .map_err(|e| anyhow!("invalid lint payload generated by hermes_lint_architecture: {e}"))?
    };

    let violations = lint_payload["violations"]
        .as_array()
        .cloned()
        .unwrap_or_default();

    let mut candidates: Vec<HealingCandidate> = violations
        .iter()
        .filter_map(|v| to_candidate(v).ok())
        .filter(|c| INITIAL_ELIGIBLE_RULES.contains(&c.rule_id.as_str()))
        .take(max_items)
        .collect();

    candidates.sort_by(|a, b| {
        let key_a = (&a.file_path, a.line_start, &a.rule_id);
        let key_b = (&b.file_path, b.line_start, &b.rule_id);
        key_a.cmp(&key_b)
    });

    let output = json!({
        "model": HEAL_MODEL,
        "dry_run": dry_run,
        "total_violations": violations.len(),
        "eligible_rules": INITIAL_ELIGIBLE_RULES,
        "eligible_count": candidates.len(),
        "candidates": candidates,
        "applied_count": 0,
        "status": if dry_run { "dry-run" } else { "planned" },
        "note": "TRACK-048 phase 1 returns constrained healing candidates. Apply mode intentionally requires explicit human review before patching."
    });
    Ok(serde_json::to_string_pretty(&output)?)
}

fn to_candidate(value: &Value) -> Result<HealingCandidate> {
    let rule_id = value["rule_id"]
        .as_str()
        .ok_or_else(|| anyhow!("missing rule_id"))?
        .to_string();
    let file_path = value["file_path"]
        .as_str()
        .ok_or_else(|| anyhow!("missing file_path"))?
        .to_string();
    let line_start = value["line_start"]
        .as_u64()
        .ok_or_else(|| anyhow!("missing line_start"))?;
    let line_end = value["line_end"].as_u64().unwrap_or(line_start);
    let severity = value["severity"]
        .as_str()
        .unwrap_or("warning")
        .to_string();
    let message = value["message"].as_str().unwrap_or("").to_string();

    Ok(HealingCandidate {
        strategy: strategy_for_rule(&rule_id).to_string(),
        rule_id,
        file_path,
        line_start,
        line_end,
        severity,
        message,
    })
}

fn strategy_for_rule(rule_id: &str) -> &'static str {
    match rule_id {
        "SAFETY-001" => "replace unwrap() with propagated Result handling",
        "SAFETY-002" => "replace expect() with error mapping and propagation",
        "SAFETY-003" => "replace any with concrete inferred type or explicit SAFETY comment",
        _ => "manual remediation required",
    }
}
